name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: cesar
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            export NODE_BIN="/home/cesar/.nvm/versions/node/v24.13.0/bin"
            export PATH="$NODE_BIN:$PATH"
            cd ~/apps/wodbuster-bot
            git pull
            $NODE_BIN/pnpm install
            $NODE_BIN/pm2 restart wodbuster-bot || $NODE_BIN/pm2 start "pnpm start" --name wodbuster-bot
